### ISSUE TITLE
MileStone Info

### ISSUE THREAD

**Issue by jessexu20** [CSC510/BadSmells#14]
I would like to get the info of the following for each milestone
open_issues = milestone['open_issues']
    closed_issues = milestone['closed_issues']
    created_at = milestone['created_at']
    updated_at = milestone['updated_at']
    closed_at = milestone['closed_at']
    due_on = milestone['due_on']

**Comment by jessexu20** [comment]
@jentle

**Comment by jessexu20** [comment]
@jentle

**Comment by jessexu20** [comment]
I think I have implemented it..

**Comment by jentle** [comment]
ok, sounds good
